package:
  name: nimble
  version: "0.2.0"

source:
  path: ../

build:
  number: 0

requirements:
  host:
    - python {{ python }}
    - setuptools
    - numpy >=1.14
    - packaging

  run:
    - python {{ python }}
    - numpy
    - packaging

outputs:
  - name: nimble

  - name: nimble-quickstart
    requirements:
      build:
      host:
        - python
        - pandas
        - scipy
        - matplotlib
        - cloudpickle
        - requests
        - h5py
        - python-dateutil
        - scikit-learn
      run:
        - python
        - pandas
        - scipy
        - matplotlib
        - cloudpickle
        - requests
        - h5py
        - python-dateutil
        - scikit-learn
        - {{ pin_subpackage('nimble', max_pin="x.x.x.x") }}
    test:
      imports:
        - nimble

test:
  imports:
    - nimble

about:
  home: https://github.com/willfind/nimble
