# Job to build the html docs for ghpages
#
# (Current) Assumptions:
# * built wheels are available using saveNameWheel
# * built conda channel availabe using saveNameConda
#
# Effects: A ghpages specific artifact containing the built site is saved.

name: Build ghpages site

on:
  workflow_call:
    inputs:
      # The name of the artifact containing the wheels
      saveNameWheel:
        required: true
        type: string
      # The name of the artifact containing the conda channel
      saveNameConda:
        required: true
        type: string
      # The name of the artifact containing the example notebooks built for the site
      saveNameNotebooks:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      # The name of the artifact containing the wheels
      saveNameWheel:
        required: true
        type: string
      # The name of the artifact containing the conda channel
      saveNameConda:
        required: true
        type: string
      # The name of the artifact containing the example notebooks built for the site
      saveNameNotebooks:
        required: true
        type: string


jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This should prep pip to use cached downloads
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: pyproject.toml

      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.saveNameWheel}}

      - name: validate wheel presence
        # test -z checks if the input is a zero length string.
        # The results of the find operation are packed into a string;
        # if not wheels are found, abort this action so we don't
        # build and deploy an empty site.
        run: if test -z "$(find . -maxdepth 1 -name "*.whl")"; then exit 1; fi

      - name: Move Wheels to docs source
        run: mv *.whl ./documentation/source/wheels

      - name: install nimble and dependencies for examples building
        run: |
          pip install nimble[quickstart] --find-links=./documentation/source/wheels
          pip install keras tensorflow

      - name: Install docs specific python dependencies
        run: pip install -r ./documentation/requirements.txt

      - name: Install pandoc system dependency via action
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19

      - name: Build site
        # our cwd is the project root, we -C to indicate the folder we want to build from/in
        run: make html -C documentation

      # save the converted notebooks of the site examples
      - uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.saveNameNotebooks}}
          path: ./documentation/html/examples
          retention-days: 1

      # pull previously created conda channel into the build site folder
      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.saveNameConda}}
          path: ./documentation/html/nimble-data

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./documentation/html
          retention-days: 1

