# Job to deploy the ghpages site via the action
#
# Assumptions:
# * actions/upload-pages-artifact has already been run, making the pages
#   artifact in-scope for this job.
#
# Effects: gh-pages site is deployed online.

name: Deploy GH-Pages site

on:
  workflow_call:

jobs:
  deploy-site:
    name: Deploy gh-pages site
    runs-on: ubuntu-latest
    needs: [build-site]
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    # This was part of the boilerplate, in order to work within an established
    # environment for deployment protection stuff. Included for best practices
    # but as far as I can tell, not really relevant to us currently?
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
