# Job to build the html docs for ghpages
#
# (Current) Assumptions:
# * remove_source.py still needs to be run on the wheels, (see the
#   repair-wheel command in pyproject.toml)
#
# Effects: A ghpages specific artifact containing the built site is saved.

name: Build ghpages site

on:
  workflow_call:
    inputs:
      # The name of the artifact containing the wheels
      saveNameWheel:
        required: true
        type: string
      # The name of the artifact containing the conda channel
      saveNameConda:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      # The name of the artifact containing the wheels
      saveNameWheel:
        required: true
        type: string
      # The name of the artifact containing the conda channel
      saveNameConda:
        required: true
        type: string


jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./documentation/html
          retention-days: 1

