# Action to publish the built docs, wheels, and examples to ghpages

name: Publish gh-pages site

# Currently, manual execution only. Eventually this will be auto triggered.
on:
  workflow_dispatch:

jobs:
  build-wheels:
    uses: ./.github/workflows/buildWheels.yml
    with:
      saveNameWheel: built_wheel
      saveNameConda: built_channel

  build-site:
    # try to build the site regardless of how much of the previous job
    # matrix completed. There are additional sanity checks within.
    if: ${{ always() }}
    needs: [build-wheels]
    uses: ./.github/workflows/buildSite.yml
    with:
      saveNameWheel: built_wheel
      saveNameConda: built_channel

  deploy-site:
    uses: ./.github/workflows/deploySite.yml
    needs: [build-site]
