name: Publish gh-pages site

on:
  workflow_dispatch:

jobs:
  buildAndSave:
#    uses: ./.github/workflows/dummy_buildAndSave.yml
    uses: ./.github/workflows/buildAndSave.yml
    with:
      saveName: built_wheels

  build-site:
    name: Make gh-pages site
    runs-on: ubuntu-latest
    needs: [buildAndSave]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: pyproject.toml
      - uses: actions/download-artifact@v3
        with:
          name: built_wheels
      - name: dependencies for wheel manipulation
        run: pip install wheel
      - name: remove source scripts for all wheels
        # small bash loop to run the script for each file that satisfies
        # the glob
        run: |
          for name in *.whl; do
              python remove_source.py . $name
          done
      - name: Move Wheels to docs source
        run: mv *.whl ./documentation/source/wheels
      - name: install nimble for examples building
        run: |
          pip install nimble[quickstart] --find-links=./documentation/source/wheels
          pip install keras tensorflow
      - name: Install docs specific python dependencies
        run: pip install -r ./documentation/requirements.txt
      - name: Install pandoc system dependency via action
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19
      - name: Build site
        # our cwd is the project root, we -C to indicate the folder we want to build from/in
        run: make html -C documentation
      - name: Check location postbuild
        run: ls documentation
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./documentation/html
          retention-days: 1

  deploy-site:
    name: Deploy gh-pages site
    runs-on: ubuntu-latest
    needs: [build-site]
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
