# edits to trigger PR workflow
name: Test Workflow

on:
  pull_request:
    branches:
      - dev
      - nini/githubActionsTests

jobs:

  build-wheels:
    uses: ./.github/workflows/buildWheels.yml
    with:
      saveNameWheel: built_wheel
      saveNameConda: built_channel

  test:
    needs: build-wheels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: pyproject.toml

      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.saveNameWheel}}
    
      - name: Move Wheels to docs source
        run: mv *.whl ./documentation/source/wheels

      - name: install nimble and dependencies
        run: 
          pip install pytest
          pip install keras tensorflow
          pip install nimble[quickstart] --find-links=./documentation/source/wheels # Only if needed 

      - name: Run pytest
        run: pytest
