# test or orchestrator 
name: PR test trigger

on:
  pull_request:
    branches:
      - dev
      - nini/githubActionsTests

jobs:
  build-wheels:
    uses: ./.github/workflows/buildWheels.yml
    with:
      saveNameWheel: built_wheel

  run-tests:
    needs: [build-wheels]
    uses: ./.github/workflows/test-workflow.yml
    with:
      saveNameWheel: built_wheel
      saveNameConda: built_channel
